// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAv_q2GD-rKOFlmnAPYyyIfRXP0TcDicZ8',
    appId: '1:900432906653:web:03ce51bb44ade268a30774',
    messagingSenderId: '900432906653',
    projectId: 'test-chat-app-61638',
    authDomain: 'test-chat-app-61638.firebaseapp.com',
    storageBucket: 'test-chat-app-61638.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDv6I4SwWB8skSqdHcXUMbuVkv0dvp7ovU',
    appId: '1:900432906653:android:028885c046598d96a30774',
    messagingSenderId: '900432906653',
    projectId: 'test-chat-app-61638',
    storageBucket: 'test-chat-app-61638.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXoy2-xFOc89mQNng6AhMoo69iPSdHGp8',
    appId: '1:900432906653:ios:f1e29a9244cd6deea30774',
    messagingSenderId: '900432906653',
    projectId: 'test-chat-app-61638',
    storageBucket: 'test-chat-app-61638.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );
}
